targets:
  $default:
    # sources:
    #   - $package$
    #   - lib/**
    #   - lib/graphql/**
    #   - lib/graphql/queries/**

    builders:
      dart_json_mapper:
        # options:
        #   iterables: List
        generate_for:
          # here should be listed entry point files having 'void main()' function
          - lib/main.dart

        # This part is needed to tell original reflectable builder to stay away
        # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files

      artemis:
        options:
          scalar_mapping:
            - graphql_type: JSON
              dart_type: Object
          schema_mapping:
            - schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries/**.graphql
              output: lib/graphql/graphql.dart
